name: "github action demo"

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: push

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ vars.APP_NAME }}
    steps:
      - run: |
          echo $GITHUB_WORKSPACE
          echo $APP_NAME
