name: "github action demo"

on: push

env:
  APP_NAME: test-app-name

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ vars.APP_NAME }}
    steps:
      - run: |
          echo $GITHUB_WORKSPACE
          echo ${{ env.APP_NAME }}
